spring:
  application:
    name: cat
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      auto-commit: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
resilience4j:
  retry:
    instances:
      externalAtelierApiRetry:
        max-attempts: 3
        wait-duration: 2s
vaadin:
  whitelisted-packages: org.csf.cat
